services:
  app:
    container_name: "wakatime_tracker.app"
    image: "wakatime_tracker.app"
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./alembic.ini:/usr/src/app/alembic.ini:ro
      - ./wakatime_tracker:/usr/src/app/wakatime_tracker:ro
      - ./scripts:/usr/src/app/scripts:ro
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    command: ["bash", "scripts/start_app.sh"]

  dashboard:
    container_name: "wakatime_tracker.dashboard"
    build:
      context: .
    ports:
      - "${DASHBOARD_PORT}:8501"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./wakatime_tracker:/usr/src/app/wakatime_tracker:ro
    environment:
      PYTHONPATH: /usr/src/app
    restart: unless-stopped
    command: [ "streamlit", "run", "wakatime_tracker/dashboard.py", "--server.port=${DASHBOARD_PORT}", "--server.address=0.0.0.0" ]

  db:
    container_name: "wakatime_tracker.db"
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
